version: "3.7"

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 4041:8080
    environment:
      - DOZZLE_TAILSIZE=100
      - VIRTUAL_HOST=dozzle.loc.dev
      - VIRTUAL_PORT=4041
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - reverse-proxy
    restart: always

networks:
  default:
    name: dozzle
  reverse-proxy:
    external: true
